[cmd/brew-update-forks] `onoe()`:  Change the comment's structure.
     The comment to which this commit message refers and which this commit modi-
fies is the one inside the mentioned function that explains what the ANSI escape
sequences used in the `echo` print statement that follows it are meant for.
This comment previously began after the end of the code it's documenting but now
preceds it.

diff --git a/cmd/brew-update-forks b/cmd/brew-update-forks
--- a/cmd/brew-update-forks
+++ b/cmd/brew-update-forks
@@ -22,8 +22,9 @@ set +o posix
 onoe() {
   if [[ -t 2 ]] # Check to see whether or not `stderr` is a TTY.  
   then
-    echo -ne "\\033[4;31mError\\033[0m:  " >&2 # Highlight 'Error' with un-
-                                               # derlining and a red color.  
+    # Print the word 'Error' in this text highlighted with underlining and a red 
+    # color:  
+    echo -ne "\\033[4;31mError\\033[0m:  " >&2
   else
     echo -n "Error:  " >&2
   fi
